### ISSUE TITLE
DRY css

### ISSUE THREAD

**Issue by rimmesbe** [hammondae/prj-rev-bwfs-dasmoto#4]
DRY (Don't Repeat Yourself). Notice how you set the color to white for all 3 h2s separately. See if you can figure out a way to extract that styling into one selector. Maybe a chained selector of some sort, or a new class.

https://github.com/hammondae/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L16

**Comment by hammondae** [comment]
Thanks, fixed!
