### ISSUE TITLE
use class here

### ISSUE THREAD

**Issue by rimmesbe** [hammondae/prj-rev-bwfs-dasmoto#5]
Good choice of tag with the strong tag (which default to bold btw). Instead of adding custom styling to the strong tag it would be better to give it a class incase we need to use the strong tag somewhere else later on. 
.price { color: blue; } 
This class is semantic.

https://github.com/hammondae/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L26-L29

**Comment by hammondae** [comment]
Thank you, strong tag changed to a class!
